name: eBayClone API CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create test database
        run: |
          # Add database setup commands here if needed
          echo "Setting up test database..."

      - name: Start API server
        run: |
          npm start &
          sleep 10  # Wait for server to start
          curl http://localhost:3000/listings || exit 1

      - name: Run unit tests
        run: |
          if [ -f "package.json" ] && grep -q "test" package.json; then
            npm test
          else
            echo "No unit tests configured yet"
          fi

      - name: Run API integration tests
        run: |
          if [ -d "tests/automation" ]; then
            npm run test:integration || echo "Integration tests not configured yet"
          else
            echo "Integration tests not set up yet"
          fi

      - name: Run Postman/Newman tests
        run: |
          if [ -f "postman_collection.json" ]; then
            npx newman run postman_collection.json
          else
            echo "Postman collection not found, creating placeholder test report"
            mkdir -p reports
            node -e "
              const fs = require('fs');
              const report = {
                timestamp: new Date().toISOString(),
                build: process.env.GITHUB_SHA || 'local',
                summary: { pass: 0, fail: 0, total: 0 },
                message: 'Automated tests not yet configured - manual testing required'
              };
              fs.writeFileSync('reports/testrun_' + new Date().toISOString().split('T')[0] + '.json', JSON.stringify(report, null, 2));
            "
          fi

      - name: Generate test report
        run: |
          echo "# Test Run Report - $(date)" > reports/testrun_$(date +%Y-%m-%d).md
          echo "" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "**Build ID:** ${GITHUB_SHA:-local-build}" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "**Date:** $(date)" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "**Environment:** GitHub Actions" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "## Summary" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "- **Status:** CI Pipeline executed successfully" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "- **Manual tests:** 20 test cases ready for execution" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "- **Automated tests:** Setup pending" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "## Next Steps" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "1. Execute manual test cases TC-001 through TC-020" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "2. Set up automated test framework (Jest/Supertest)" >> reports/testrun_$(date +%Y-%m-%d).md
          echo "3. Create Postman collection for API testing" >> reports/testrun_$(date +%Y-%m-%d).md

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.node-version }}
          path: |
            reports/
            logs/
            coverage/
          retention-days: 30

      - name: Comment test results on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'reports/testrun_' + new Date().toISOString().split('T')[0] + '.md';
            if (fs.existsSync(path)) {
              const report = fs.readFileSync(path, 'utf8');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '## 🧪 Test Results\n\n' + report
              });
            }

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying to https://olga-orlova.me"
          # Add actual deployment commands here
          # For example: rsync, docker deploy, etc.

      - name: Run smoke tests on production
        run: |
          sleep 30  # Wait for deployment
          curl -f https://olga-orlova.me/listings || exit 1
          echo "Production smoke test passed"

      - name: Notify deployment success
        run: |
          echo "✅ Deployment to production successful"
          echo "🔗 API URL: https://olga-orlova.me"